max_width = 192              # Max line width

#use_small_heuristics = "Max" # Avoid collapsing small blocks inline
#use_small_heuristics = "Default"

edition = "2021"             # Make sure it matches your Rust edition
reorder_imports = true       # Sort imports automatically

#format_code_in_doc_comments = true # Format Rust code blocks in doc comments

# Group imports into standard library, external crates, and local modules,
# and insert a blank line between each group for better readability.
# group_imports = "StdExternalCrate"


# Force method chains (like builder patterns) to always be formatted over multiple lines,
# regardless of whether they would fit within the max_width limit.
# This is useful for improving readability and consistency, especially with builder-style APIs.
#chain_width = 640

# UNSTABLE

# Maximum number of blank lines which can be put between items. If more than this number of consecutive empty lines are found, they are trimmed down to match this integer.
#blank_lines_upper_bound = 4

#imports_granularity = "Module"  # or "Crate", "Item", etc.
#group_imports = "StdExternalCrate"  # or "One", "Preserve"
# force_multiline_blocks = true
# overflow_delimited_expr = true
